package com.github.protocolfuzzing.edhocfuzzer;

public enum MessageInputTypeRA {
    EDHOC_MESSAGE_1_INPUT,
    EDHOC_MESSAGE_2_INPUT,
    EDHOC_MESSAGE_3_INPUT,
    EDHOC_MESSAGE_4_INPUT,
    EDHOC_ERROR_MESSAGE_INPUT,
    EDHOC_MESSAGE_3_OSCORE_APP_INPUT,
    OSCORE_APP_MESSAGE_INPUT,
    COAP_APP_MESSAGE_INPUT,
    COAP_EMPTY_MESSAGE_INPUT
}
