#!/usr/bin/env bash

readonly SCRIPT_DIR="$(cd -- $(dirname -- ${BASH_SOURCE[0]}) >/dev/null 2>&1 && pwd)"
readonly BASE_DIR="$(dirname -- ${SCRIPT_DIR})"

usage() {
  cat << END
  Usage: ${0##*/} [-opt]
  Options:
    -l  Fetch and setup cf-edhoc library
    -h  Show usage message
END
  exit 0
}

setup_library() {
    # setup cf-edhoc library

    readonly PATCH_FILE="${SCRIPT_DIR}/cf-edhoc.patch"
    readonly COMMIT_HASH="723c652947bf22507dc10a72416d7896dcbc3649"

    set -e
    cd ${BASE_DIR}
    git clone "https://github.com/rikard-sics/californium.git"
    cd californium
    git checkout edhoc
    git checkout ${COMMIT_HASH}
    git apply ${PATCH_FILE}
    mvn package -DskipTests -am -pl cf-edhoc
    JAR_FILE=$(ls ./cf-edhoc/target/cf-edhoc-*-SNAPSHOT.jar)

    mvn install:install-file \
        -Dfile=${JAR_FILE} \
        -DgroupId=se.ri.org.eclipse.californium \
        -DartifactId=cf-edhoc \
        -Dversion=0.0.0 \
        -Dpackaging=jar

    cd ${BASE_DIR}
    rm -rf ./californium/
    set +e
}

setup_fuzzer() {
    # package project and create symlink

    set -e
    cd ${BASE_DIR}
    mvn clean package
    ln -sf ${BASE_DIR}/target/edhoc-fuzzer-*-jar-with-dependencies.jar edhoc-fuzzer.jar
    set +e
}


while getopts :lh flag
do
  case "${flag}" in
    l) setup_library ;;
    : | \? | h | *) usage ;;
  esac
done

setup_fuzzer
